---

# name: Remove default Logstash filters
- file: state=absent path=/etc/logstash/conf.d/
- file: state=directory path=/etc/logstash/conf.d/

- name: Create Logstash filters.
  copy:
    src: "{{ item }}"
    dest: "/etc/logstash/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - tcp-syslog-json.conf
  notify: restart logstash